title: My Own Repo!
email: guare4business@gmail.com
baseurl: "/" 
url: "https://gu4re.github.io" 
domain: gu4re.github.io
github_username:  gu4re

header_pages:
  - index.md
  - github.md
  - contact.md

# Build settings
style: hacker
listen_for_clients_preferred_style: false
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache
